# Write the 10 s follow-up runner for a two-group cord screen (cordx6.bend layout and later):
# the screen's own kernel and axes, sixteen members from ext/<screen>/picks.json (eight per
# row-set group), each run with the screen's seed and a fresh one.
#
#   node scripts/cord_rhythm.mjs --screen x7 --wiring real      # writes the picks
#   python3 scripts/cord_long_bend.py --screen x7               # writes cordx7L.bend
#   bend cordx7L.bend -o cordx7L && node scripts/cord_rhythm_long.mjs --screen x7 run
import json
import argparse


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--screen", required=True)
    a = ap.parse_args()
    sc = a.screen
    s = open(f"cord{sc}.bend").read()
    picks = json.load(open(f"ext/{sc}/picks.json"))["picks"]
    assert len(picks) == 2 and all(len(p) == 8 for p in picks)
    assert all(0 <= m < 64 for m in picks[0]) and all(64 <= m < 128 for m in picks[1])

    def rep(old, new):
        nonlocal s
        assert s.count(old) == 1, old[:80]
        s = s.replace(old, new)

    head = s[:s.index("import Base")]
    s = (f"# Long-run follow-up to cord{sc}.bend, generated by scripts/cord_long_bend.py: sixteen\n"
         f"# members from ext/{sc}/picks.json ({picks[0]} at loop x1, {picks[1]} at x3), 10 s under the\n"
         "# command, each with the screen's seed and a fresh one. The screen-seed run's first 4000\n"
         "# steps must equal the screen's run. The screen's own header follows.\n#\n" + head
         + s[s.index("import Base"):])
    rep("def Ens.steps() -> U32:\n  4000", "def Ens.steps() -> U32:\n  20000")
    rep("def Ens.members() -> U32:\n  128", "def Ens.members() -> U32:\n  16")
    rep(f'"ext/{sc}/cur/{sc}_search.bin"', f'"ext/{sc}/cur/{sc}_long.bin"')
    pick = lambda xs: ", ".join(str(x) for x in xs)
    rep('''# run index within a row-set group -> member and condition: group g holds members 64g..64g+63
def Run.member(+j: U32, +grp: U32) -> U32:
  (grp * 64 + U32.shrn(j, 1n) : U32)''', f'''# the chosen members: group 0 (loop x1) then group 1 (loop x3)
def Pick.at(+k: U32, +a0: U32, +a1: U32, +a2: U32, +a3: U32, +a4: U32, +a5: U32, +a6: U32, +a7: U32) -> U32:
  Bool.pick(U32, U32.is_eq(k, 0), a0, Bool.pick(U32, U32.is_eq(k, 1), a1,
    Bool.pick(U32, U32.is_eq(k, 2), a2, Bool.pick(U32, U32.is_eq(k, 3), a3,
      Bool.pick(U32, U32.is_eq(k, 4), a4, Bool.pick(U32, U32.is_eq(k, 5), a5,
        Bool.pick(U32, U32.is_eq(k, 6), a6, a7)))))))

def Pick.m(+g: U32, +k: U32) -> U32:
  Bool.pick(U32, U32.is_eq(g, 0), Pick.at(k, {pick(picks[0])}),
    Pick.at(k, {pick(picks[1])}))

# run index within a group -> member, and the seed slot in place of the condition
def Run.member(+j: U32, +grp: U32) -> U32:
  Pick.m(grp, U32.shrn(j, 1n))''')
    rep('''  Lane.start(driven, pL, pR, pO, K, n, Cfg.of(m, c), (2654435761 + m * 7919 + c : U32), rows,
    chan, dc, Cells.build(hl, role, prop, sign, cmd, n, Cfg.of(m, c)))''', '''  Lane.start(driven, pL, pR, pO, K, n, Cfg.of(m, 0),
    Bool.pick(U32, U32.is_eq(c, 0), (2654435761 + m * 7919 : U32), (2246822519 + m * 104729 : U32)),
    rows, chan, dc, Cells.build(hl, role, prop, sign, cmd, n, Cfg.of(m, 0)))''')
    open(f"cord{sc}L.bend", "w").write(s)
    print(f"cord{sc}L.bend: picks {picks}")


if __name__ == "__main__":
    main()
