# Write cordx8L.bend, the 10 s follow-up to cordx8.bend (docs/54): eight lower-bit settings from
# ext/x8/picks.json, each run under row-sets 0 (x1), 3 (within-hemilineage x0) and 7 (own half x0),
# 10 s under the command, with the screen's seed and a fresh one.
#
#   node scripts/cord_scale_picks.mjs && python3 scripts/cord_long_x8.py
#   bend cordx8L.bend -o cordx8L && node scripts/cord_scale_long.mjs run
import json


def main():
    s = open("cordx8.bend").read()
    P = json.load(open("ext/x8/picks.json"))
    rs, picks = P["rowsets"], P["picks"]
    assert rs == [0, 3, 7] and len(picks) == 3 and all(len(p) == 8 for p in picks)
    assert all(m // 32 == g for g, p in zip(rs, picks) for m in p)
    lo = [m % 32 for m in picks[0]]
    assert all([m % 32 for m in p] == lo for p in picks)

    def rep(old, new):
        nonlocal s
        assert s.count(old) == 1, old[:80]
        s = s.replace(old, new)

    head = s[:s.index("import Base")]
    s = ("# Long-run follow-up to cordx8.bend, generated by scripts/cord_long_x8.py: lower-bit settings\n"
         f"# {lo} from ext/x8/picks.json under row-sets {rs}, 10 s under the command, each with the\n"
         "# screen's seed and a fresh one. The screen-seed run's first 4000 steps must equal the\n"
         "# screen's run. The screen's own header follows.\n#\n" + head + s[s.index("import Base"):])
    rep("def Ens.steps() -> U32:\n  4000", "def Ens.steps() -> U32:\n  20000")
    rep("def Ens.members() -> U32:\n  256", "def Ens.members() -> U32:\n  24")
    rep('"ext/x8/cur/x8_search.bin"', '"ext/x8/cur/x8_long.bin"')
    a = ", ".join(str(x) for x in lo)
    rep('''# run index within a row-set group -> member and condition: group g holds members 32g..32g+31
def Run.member(+j: U32, +grp: U32) -> U32:
  (grp * 32 + U32.shrn(j, 1n) : U32)''', f'''# the long run's three groups are the screen's row-sets {rs}
def Grp.rs(+g: U32) -> U32:
  Bool.pick(U32, U32.is_eq(g, 0), {rs[0]}, Bool.pick(U32, U32.is_eq(g, 1), {rs[1]}, {rs[2]}))

def Pick.at(+k: U32, +a0: U32, +a1: U32, +a2: U32, +a3: U32, +a4: U32, +a5: U32, +a6: U32, +a7: U32) -> U32:
  Bool.pick(U32, U32.is_eq(k, 0), a0, Bool.pick(U32, U32.is_eq(k, 1), a1,
    Bool.pick(U32, U32.is_eq(k, 2), a2, Bool.pick(U32, U32.is_eq(k, 3), a3,
      Bool.pick(U32, U32.is_eq(k, 4), a4, Bool.pick(U32, U32.is_eq(k, 5), a5,
        Bool.pick(U32, U32.is_eq(k, 6), a6, a7)))))))

# run index within a group -> the screen's member, and the seed slot in place of the condition
def Run.member(+j: U32, +grp: U32) -> U32:
  (Grp.rs(grp) * 32 + Pick.at(U32.shrn(j, 1n), {a}) : U32)''')
    rep('''  Lane.start(driven, pL, pR, pO, K, n, Cfg.of(m, c), (2654435761 + m * 7919 + c : U32), rows,
    chan, dc, Cells.build(hl, role, prop, sign, cmd, n, Cfg.of(m, c)))''', '''  Lane.start(driven, pL, pR, pO, K, n, Cfg.of(m, 0),
    Bool.pick(U32, U32.is_eq(c, 0), (2654435761 + m * 7919 : U32), (2246822519 + m * 104729 : U32)),
    rows, chan, dc, Cells.build(hl, role, prop, sign, cmd, n, Cfg.of(m, 0)))''')
    rep('''        IO.print("row-set group " ++ U32.show(g) ++ " factor " ++ F32.show(Comm.factor(g)))''',
        '''        IO.print("row-set " ++ U32.show(Grp.rs(g)) ++ " factor " ++ F32.show(Comm.factor(Grp.rs(g))))''')
    rep("Rows.build(lens, g, Comm.factor(g), gaps", "Rows.build(lens, Grp.rs(g), Comm.factor(Grp.rs(g)), gaps")
    rep("(Ens.members() * Ens.conds() : U32), 8), Ens.batch()", "(Ens.members() * Ens.conds() : U32), 3), Ens.batch()")
    rep("    r : ROut <- Groups.go(8n, 0,", "    r : ROut <- Groups.go(3n, 0,")
    open("cordx8L.bend", "w").write(s)
    print(f"cordx8L.bend: lower bits {lo} under row-sets {rs}")


if __name__ == "__main__":
    main()
